### ISSUE TITLE
Select unified code style for object literals

### ISSUE THREAD

**Issue by terbooter** [test-metrika/web#6]
@black-roland  style
```
dotenv.config({ silent: true });
```
uses spaces between curly braces.
mine not
```
dotenv.config({silent: true});
```

Any coding style from big guys?

**Comment by black-roland** [comment]
Unfortunately, `tslint` doesn't have default rules related to this situation. So I looked at [Github top 3 trending repositories](https://github.com/trending/typescript):
- https://github.com/Microsoft/vscode
- https://github.com/angular/angular
- https://github.com/ant-design/ant-design

I didn't find clear guidelines about braces, but I explored the code and found what whitespaces are commonly used. For example:
- https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/menus.ts#L314
- https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx#L98

In Angular code whitespaces not used.

I think Microsoft style is preferable and we should use curly braces with whitespaces:

```
dotenv.config({ silent: true });
```

**Comment by terbooter** [comment]
Agreed.
I setted new coding styles for IDE.
("Object literal braces" rule for IntelliJ Idea)

**Comment by sergey-akhalkov** [comment]
@black-roland, @terbooter you should use 
```javascript
dotenv.config({ silent: true });
```
code style. Please let's discuss code style issues/questions here.
