### ISSUE TITLE
Lets make config more simple

### ISSUE THREAD

**Issue by terbooter** [test-metrika/web#7]
I suggest name config properties same as environment variables
So this
```
{
    [constants.serverConfig.NODE_ENV]: env.NODE_ENV,
}
```
will turn into
```
{
    NODE_ENV: env.NODE_ENV,
}
```
If envvar will collide with already existing we can use prefix.
`WEB_MONGO_HOST` or ` WEB_MONGO_PORT`

**Comment by black-roland** [comment]
Constants are used here for static analyze, not because of collisions. Your application won't compile if you missed something. Also with constants you get handy autocomplete in IDE.

Constants are useful not only for config files. For example, you can use it with [IoC](http://inversify.io/).

**Comment by sergey-akhalkov** [comment]
As of now, I'm in favor of using the simplest way to store config values, so let's use 
```
{
    "NODE_ENV": env.NODE_ENV
}
```

**Comment by black-roland** [comment]
Seems you don't quite understand why constants are used. Please see [this StackOverflow question](https://softwareengineering.stackexchange.com/q/250619) and especially [this answer](https://softwareengineering.stackexchange.com/a/250639). Since we use TypeScript (not simply JavaScript), constants make sense, for tiny projects too.

**Comment by sergey-akhalkov** [comment]
@black-roland, do I get it right if you are going to use the following approach:
```typescript
export class AppSettings {
   public static API_ENDPOINT='http://127.0.0.1:6666/api/';
}
```
?

**Comment by black-roland** [comment]
@sergey-akhalkov something like that but using IoC (InversifyJS).

So later in code I can inject this config variables:

```typescript
class TestController {
    @inject(constants.CONFIG) @named(constants.API_ENDPOINT)
    private apiEndpoint: string;
}
```

**Comment by sergey-akhalkov** [comment]
@black-roland, looks good, thanks for the clarification.

**Comment by terbooter** [comment]
@black-roland I think that using IoC is over-engineering for small projects. (As we saw Mobile Center does not use it.) It brings to much magic.
Injecting private fields especially dangerous, because this class cant be tested without IoC container.

May be my opinion is wrong. But I had bad experience with Parsley IoC for AS3.
Anyway this decision is up to team leader.

**Comment by sergey-akhalkov** [comment]
@terbooter, @black-roland, are you still working on this test app? Let's stop discussions and implementation. It would be much better if both of you will investigate hockey app features and center source code. 
Regarding to config implementation - I'm agree with @terbooter that using IoC is over-engineering for such small project.
