### ISSUE TITLE
gulp config back to single file

### ISSUE THREAD

**Issue by terbooter** [test-metrika/web#8]
I played with multifile gulp config variant and found that it has more "cons" then "pros" 

Minuses:
* Extra folder and files
* No context. Its like `eval()` inject code in code.
* IDE cant jump to declaration
* Not mainstream. [gulp-hub](https://github.com/frankwallis/gulp-hub) has only 63 starts 

Pluses:
* In a sense code looks more organized
* Very big config might be more readable divided to several files

**Comment by black-roland** [comment]
> Extra folder and files

Why is it a problem? Could you be more specific?

> No context. Its like eval() inject code in code.
> IDE cant jump to declaration

Yeah, I agree with you. As a solution, we can drop `gulp-hub` and use plain function and imports. [Like AngularJS doing](https://github.com/angular/angular/blob/master/gulpfile.js#L30) but without dynamic require.

> Not mainstream. gulp-hub has only 63 starts

I don't think what 63 stars is not enough. Especially stars is a weird indicator of a mainstream.

**Comment by sergey-akhalkov** [comment]
@terbooter, @black-roland, `react-native-code-push` project successfully uses [single gulp file](https://github.com/Microsoft/react-native-code-push/blob/master/gulpfile.js). I think gulp file should be divided into pieces only in case of complexity and file size. As of now to make things as simple as possible you could you single gulp file.
